### ISSUE TITLE
Unbounded source and grouping

### ISSUE THREAD

**Issue by sparkofreason** [atdixon/thurber#1]
I have a feeling this is an issue with DirectRunner (or my noobidity), not thurber, but giving it a shot here anyway. The flow below will not give any output. If I remove the `GroupByKey`, it does. Same thing happens trying to write to file.

```clojure
(def pipeline
  (-> (th/create-pipeline {:streaming true :block-on-run false})
      (doto
       (th/apply!
            (read-pubsub-subscription "projects/my-project/my-sub")
            #'decode-json
            (WithTimestamps/of (th/ser-fn #'timestamp))
            (th/partial #'th/->kv :traceId)
            (-> (Window/into
                 (Sessions/withGapDuration (Duration/standardSeconds 1))))
            (GroupByKey/create)
            #'println))))
```

**Comment by atdixon** [comment]
@sparkofreason 

Couple of possibilities:

* Your timestamp assignments (via `#'timestamp`) may not be causing your session windows to close.
* You may be getting an exception somewhere (if so, likely with the timestamp assignments) but with `DirectRunner` + `:block-on-run false` you won't see them thrown out from the `.run`
* I believe `WithTimestamps` will throw if you regress the timestamp back (you can only legally move it _forward_ from the timestamp that `PubsubIO` assigns)

Here's a working demo of your use case w/o Pubsub:

```
(ns simple.repro
  (:require [thurber :as th]
            [clj-time.core :as t])
  (:import (org.apache.beam.sdk.transforms WithTimestamps GroupByKey)
           (org.apache.beam.sdk.transforms.windowing Window Sessions BoundedWindow)
           (org.joda.time Duration)))

(defn- timestamp [elem]
  (.toInstant (t/now)))

(defn- build-pipeline! [pipeline]
  (doto pipeline
    (doto
      (th/apply!
        (th/create [{:traceId 100 :payload "hello"}
                    {:traceId 200 :payload "goodbye"}
                    ::marker])
        (WithTimestamps/of (th/ser-fn #'timestamp))
        (th/partial #'th/->kv :traceId)
        (-> (Window/into
              (Sessions/withGapDuration
                (Duration/standardSeconds 1))))
        (GroupByKey/create)
        #'th/log-verbose))))

(defn demo! []
  (->
    (th/create-pipeline {:streaming true :block-on-run true})
    (build-pipeline!)
    (.run)))
```

**Comment by sparkofreason** [comment]
Thanks. That definitely works. I tried getting rid of `WithTimestamps` to just take the default, still no output in the unbounded case. Messages are getting consumed from Pub/Sub, and I don't think there are any exceptions, unless they're getting sent someplace mysterious (I've done `Thread/setDefaultUncaughtExceptionHandler`). Comment the `GroupByKey`, and I get output.

Unless you have any further thoughts, I'm going to guess this really is a DirectRunner issue, probably best solved by collecting test data and using bounded collections for local dev. Closing.

**Comment by atdixon** [comment]
I assume you've got data flowing into the pubsub topic. You have the 1-second gap duration - so as long as your `:traceId` goes quiet for at least a second AND the pubsub watermark progresses then you should see the GroupBy aggregation emit. Good luck.

**Comment by sparkofreason** [comment]
I was able to dump the Pub/Sub messages to a file, and then consumed that with the above pipeline, timestamps and all. Worked fine, so I do think this is something weird in DirectRunner.

**Comment by atdixon** [comment]
Interesting, it appears there is a different `PubsubIO` reference implementation for non-Dataflow runners, including `DirectRunner`: https://cloud.google.com/dataflow/docs/concepts/streaming-with-cloud-pubsub#integration-features

As a side note I played with your example more -- I can get the `GroupBy` to fire if I configure early-triggering -- but it looks like the watermark behavior to get the single on-time firing is broken as you've pointed out. It appears you're correct, the Dataflow `PubsubIO` is for Dataflow-only.

**Comment by sparkofreason** [comment]
I think I am using that reference `PubsubIO` impl, my `:import` looks like `(org.apache.beam.sdk.io.gcp.pubsub PubsubIO PubsubMessage PubsubMessageWithAttributesCoder)`.  I did have a dep for `com.google.cloud/google-cloud-pubsub`, removed that, same behavior.

On a different project, using datasplash, I had seen similar behavior. I was also able to hack around it by early triggering. The same code deployed to Dataflow would run fine. datasplash does enough intervening stuff that I wasn't convinced that the issue lay in Beam. thurber is thin enough that pretty much all doubt is removed. Odd that I can't find any other mention of this issue via Google. At some point I'll try a non-pubsub unbounded source, and see if the problem persists.

**Comment by sparkofreason** [comment]
Another workaround shown below. Since this works, and is unbounded, then I guess you're right and the issue is with `PubsubIO`. Also, some sugar around an unbounded source created from a core.async channel might be a nice feature, for testing/local dev.

```clojure
(defn seq!!
  "Returns a (blocking!) lazy sequence read from a channel."
  [c]
  (lazy-seq
   (when-let [v (<!! c)]
     (cons (with-meta v {:th/event-timestamp (timestamp v)}) (seq!! c)))))

(def c (async/chan 10000))
(defn span-seq
  []
  (seq!! c))

(def pubsub->chan
  (-> (th/create-pipeline {:streaming true :block-on-run false})
      (doto
       (th/apply!
            (read-pubsub-subscription "projects/ck-development-platform/subscriptions/ck-deputy-zipkin-spans-subscription")
            #'decode-json
            (th/fn* ->c [v] (async/put! c v) v)))))

(def pipeline
  (-> (th/create-pipeline {:streaming true :block-on-run false})
      (doto
       (th/apply!
           (Read/from (UnboundedSeqSource/create #'span-seq))
            #_#'decode-json
            (WithTimestamps/of (th/ser-fn #'timestamp))
            (th/partial #'th/->kv :traceId)
            (-> (Window/into
                 (Sessions/withGapDuration (Duration/standardSeconds 10)))
                #_(.discardingFiredPanes))
            (GroupByKey/create)
            #'th/kv->clj
            (th/fn* spew [[k v]] (swap! traces assoc k v))))))
```

**Comment by atdixon** [comment]
Nice! `UnboundedSeqSource` was an early attempt to get to a channel-based source. Well done.

It seems that Beam [Splittable DoFn](https://beam.apache.org/blog/2017/08/16/splittable-do-fn.html)s are the new way to custom-implement unbounded sources -- [demo/splittable_dofn.clj](https://github.com/atdixon/thurber/blob/master/demo/simple/splittable_dofn.clj) has some docs showing how to interactively send stuff into a pipeline from a Clojure REPL. Not sure where these two approaches go/consolidate to.

**Comment by sparkofreason** [comment]
Gave the splittable thing a shot. This seems to work, maybe a bit brain-dead. Causes the CPU to smoke, so I probably missed something.

```clojure
(def c (async/chan 10000))

(def ^Duration resume-delay (Duration/millis 250))

(def i (atom 0))

(defn process-restriction
  [_]
  (loop [span (async/poll! c)]
    (if (some? span)
      (let [timestamp (zdf/timestamp span)]
        (.tryClaim (th/*restriction-tracker) (swap! i inc))
        (.outputWithTimestamp (th/*process-context) span timestamp)
        (.updateWatermark (th/*process-context) timestamp)
        (recur (async/poll! c)))
      (-> (DoFn$ProcessContinuation/resume)
          (.withResumeDelay resume-delay)))))
```

**Comment by atdixon** [comment]
Brilliant. You prob need to handle `.tryClaim` returning false, but I think you'll still see the CPU spike.

I profiled DirectRunner, I think it is simply CPU-aggressive. Your previous UnboundedSeqSource + channel is blocking on the channel read, I suspect if that was made non-blocking somehow you'd see the CPU spin.

I wonder how https://cloud.google.com/pubsub/docs/emulator would fare with a local DirectRunner.

**Comment by sparkofreason** [comment]
Interesting. I verified the CPU behavior, in this case by validating that `process-restriction` is only called every 250ms. So the work is happening somewhere else. Tried to make the splittable DoFn blocking just for giggles. I didn't really think that would work, and it didn't.

Is the splittable DoFn stuff documented someplace? The best I've found so far is a high-level blog post from 2017.

**Comment by atdixon** [comment]
Afaict, it's that blog post + javadoc, perhaps there is more on the Beam
mailing lists archives. I just found this as well:
https://cwiki.apache.org/confluence/display/BEAM/Design+Documents

Looking @ the DirectRunner code, there is no sleep/IO/etc -- the
DirectRunner processes in a loop, repeatedly submitting work to an executor
pool w/ no IO or delays. Even the implementation of resumeDelay does not
result in any sleep, so increasing that doesn't change the dynamics either

**Comment by sparkofreason** [comment]
Nice to have might be some notion of "partial" for the `process-restriction` function. I was trying to factor this implementation into something reusable, but that would require that `process-restriction` get passed the instance of the channel, rather than just grabbing a var from the environment.

**Comment by atdixon** [comment]
`TDoFn_Splittable_Unbounded` hasn't yet been integrated into `thurber/apply!` but you can stil get partial args through.

Here is the `ParDo` in [the demo](https://github.com/atdixon/thurber/blob/master/demo/simple/splittable_dofn.clj):

```
(def thingy-xf
  (ParDo/of
    (TDoFn_Splittable_Unbounded. #'process-restriction #'init-restriction #'get-tracker)))
```

To pass partial args through to the `#'process-restriction` you can provide an array of args to `TDoFn_Splittable_Unbounded`:

`(TDoFn_Splittable_Unbounded. #'process-restriction #'init-restriction #'get-tracker (into-array Object [:some-arg]))`

Then these values will applied to the first n args of the process function.

**Comment by sparkofreason** [comment]
Nice. In retrospect I should have figured that out, I was staring right at the implementation. Thanks.
