### ISSUE TITLE
https://beamsummit.org/ -- ?

### ISSUE THREAD

**Issue by brucearctor** [atdixon/thurber#11]
https://beamsummit.org/ ?

Not sure how much this is still in use/development.

I also need to try myself ( only just discovered ).

Encouraging, if this is still active, to consider sharing this year at https://2022.beamsummit.org/  ( I was writing this for no matter where you lived, but it looks like you might actually be based in Austin, so even easier ).

**Comment by atdixon** [comment]
Just seeing this. Thanks for the prompt. I am in Austin. For a while, I had time to track Apache Beam releases, but haven't been able to do that the past year as I've been preoccupied with some other professional work. I'll take a look at the summit and consider if I have some time to pitch a proposal. Thanks again!

**Comment by brucearctor** [comment]
Definitely -- and even without a presentation, perhaps see you at the summit and/or happy to connect when on ground outside of that ( you can reach me at austin@bamboozoology.org )
