### ISSUE TITLE
Partial application for combiner functions?

### ISSUE THREAD

**Issue by sparkofreason** [atdixon/thurber#3]
This does not work:

```clojure
(defn map-stats-combiner
  [ks]
  (th/combiner
   (th/fn* extract-map-stats [acc]
           (reduce (fn [x [k v]] (assoc x k (extract-stats v))) {} acc))
   (th/partial #'combine-stats-by-keys ks)
   (th/partial #'reduce-map-stats ks)))
```

Error: `java.lang.AssertionError : "Assert failed: (var? combinef)"`.

**Comment by atdixon** [comment]
This is a good use case. Will take a bit to implement it in a sane fashion.

I demonstrated a workaround here:
https://github.com/atdixon/thurber/blob/master/demo/simple/proxy_foo.clj

Let me know what you think.

**Comment by sparkofreason** [comment]
Nice, that's handy. FWIW, I did the same thing using proxy-plus. Claims to be faster/better than `proxy`, haven't tested for this use case.

https://github.com/redplanetlabs/proxy-plus

**Comment by atdixon** [comment]
thurber now supports `th/partial` functions provided to `th/combiner`; as of this release: https://github.com/atdixon/thurber/releases/tag/0.0.4-alpha3

**Comment by sparkofreason** [comment]
Finally got around to using this instead of the proxy, works great!
