### ISSUE TITLE
NotSerializableException when using spec instrumentation

### ISSUE THREAD

**Issue by sparkofreason** [atdixon/thurber#4]
Should have been obvious in retrospect, but I tried to use spec to instrument my functions, got `java.io.NotSerializableException : "clojure.spec.alpha$fspec_impl$reify__2524"` when calling `apply!`. Not sure that this is fixable (or worth bothering). Would be nice to have for testing, I suppose, and probably worth a note in the docs.

**Comment by atdixon** [comment]
I didn't think about spec but I bet it would be quite useful to be able validate specs through a pipeline execution. I tried a few examples of spec and did not encounter an issue:

```
(ns simple.with-spec
  (:require [thurber :as th]
            [clojure.string :as str]
            [clojure.spec.alpha :as s]
            [clojure.spec.test.alpha :as stest]
            [clojure.tools.logging :as log]))

(s/def ::raw-elem string?)

(defn- custom-reverse [elem]
  (log/info
    (s/valid? ::raw-elem elem))
  (str/reverse elem))

(s/fdef custom-reverse
  :args (s/cat :elem string?)
  :ret string?)

(stest/instrument `custom-reverse)

(defn- build-pipeline! [pipeline]
  (doto pipeline
    (th/apply!
      (th/create ["hello" "world"])
      #'custom-reverse
      #'th/log)))

(defn demo! []
  (-> (th/create-pipeline) build-pipeline! .run))
```

However here are registered spec keywords not first-class spec objects. Can you share an example that reproduces this error?

**Comment by sparkofreason** [comment]
Not nearly as simple as I thought. The key was in this:

```clojure
(Combine/perKey
      (th/proxy* #'map-stats-combiner {:duration_us :duration_us
                                       :rows rows}))
```
Here `rows` is a function. If there is an `fspec` defined for rows, I get the error, otherwise not. So that's pretty good, since I can still use spec on the main functions in the pipeline definition.

**Comment by atdixon** [comment]
A developing idiom in thurber is to always pass functions as vars. This way you can be fully explicit about what gets serialized (e.g., via the serializabel args passed to `th/partial` and `th/proxy*`).

So here for example if you can pass `rows` as a function `var` then you should not see the error.

**Comment by atdixon** [comment]
And Clojure has a nice property where vars that refer to functions don't need to be de-refed when used as function invocation.

E.g.,

```
(defn foo [] 1234)

(assert (= (#'foo) (foo) 1234))
```

**Comment by sparkofreason** [comment]
Yeah, that did it. Thanks.
